# Ansible Playbook to install Zabbix Server in a playground situation (NON-PROD)
# Required: ansible-galaxy collection install community.mysql
---
- hosts: localhost
  become: yes
  vars:
    system_user: 'ec2-user'
    common_name: 'zabbix-rcs.cscdevops.com'
    ansible_python_interpreter: '/usr/bin/python3'
  tasks:
    - name: Add Zabbix repository
      ansible.builtin.shell: rpm -Uvh https://repo.zabbix.com/zabbix/6.4/rhel/8/x86_64/zabbix-release-6.4-1.el8.noarch.rpm
      args:
        creates: /etc/yum.repos.d/zabbix.repo

    - name: Modify php version
      shell: dnf module switch-to php:7.4 -y

    - name: Install required packages
      ansible.builtin.dnf:
        name:
          - 'zabbix-server-mysql'
          - 'zabbix-web-mysql' 
          - 'zabbix-apache-conf' 
          - 'zabbix-sql-scripts' 
          - 'zabbix-selinux-policy'
          - 'zabbix-agent'
          - 'python3-pip'
          - 'unzip'
          - 'mysql-server'
          - 'jq'
          - 'wget'
          - 'python3-PyMySQL'
        state: present
        update_cache: yes

    - name: Start and enable mysql service
      ansible.builtin.systemd:
        name: mysqld
        state: started
        enabled: yes
        daemon_reload: no

    - name: Create database
      mysql_db: 
        db=zabbixdb 
        state=present

    - name: Create database user
      mysql_user: 
        user=zabuser 
        password=zabpass 
        priv=zabbixdb.*:ALL 
        state=present

    - name: Set Global DB Variable before import
      mysql_query:
        login_db: zabbixdb
        query: set global log_bin_trust_function_creators = 1

    - name: Import database dump
      mysql_db:
        state: import
        login_user: zabuser
        login_password: zabpass
        name: zabbixdb
        encoding: utf8mb4
        target: /usr/share/zabbix-sql-scripts/mysql/server.sql.gz

    - name: Set Global DB Variable after import
      mysql_query:
        login_db: zabbixdb
        query: set global log_bin_trust_function_creators = 0

    - name: Set DB name in Zabbix config
      lineinfile:
        path: /etc/zabbix/zabbix_server.conf
        regexp: '^DBName='
        line: DBName=zabbixdb

    - name: Set DB user in Zabbix config
      lineinfile:
        path: /etc/zabbix/zabbix_server.conf
        regexp: '^DBUser='
        line: DBUser=zabuser

    - name: Set DB password in Zabbix config
      lineinfile:
        path: /etc/zabbix/zabbix_server.conf
        insertbefore: '^### Option: DBSocket'
        regexp: '^DBPassword='
        line: DBPassword=zabpass
        state: present

    - name: Set DB password in Zabbix config
      lineinfile:
        path: /etc/zabbix/zabbix_server.conf
        insertafter: '^# AllowUnsupportedDBVersions=0'
        regexp: '^AllowUnsupportedDBVersions='
        line: AllowUnsupportedDBVersions=1
        state: present

    - name: Start and enable Zabbix Server service
      ansible.builtin.systemd:
        name: zabbix-server
        state: started
        enabled: yes
        daemon_reload: no

    - name: Start and enable Zabbix Agent service
      ansible.builtin.systemd:
        name: zabbix-agent
        state: started
        enabled: yes
        daemon_reload: no

    - name: Start and enable mysql service
      ansible.builtin.systemd:
        name: httpd
        state: started
        enabled: yes
        daemon_reload: no

    - name: Start and enable php-fpm service
      ansible.builtin.systemd:
        name: php-fpm
        state: started
        enabled: yes
        daemon_reload: no

